[build]
  command = "mise install && mise use -g python 3.10.13 && python -m pip install --upgrade pip && python -m pip install -r requirements.txt"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.10"
